### ISSUE TITLE
Time-frame for QGIS3?

### ISSUE THREAD

**Issue by timcera** [spark-hydro/qswatmod-deprecated#1]
Just getting started using SWAT-MODFLOW and would like to use QSWATMOD.  However we have been using QGIS3 for some time now.  Wondered what the time-frame might be for QSWATMOD with QGIS3?

Also, I might be able to help.  I haven't worked on a QGIS plugin, however I am a pretty good with Python.

**Comment by spark-hydro** [comment]
I should've announced that a new version of QSWATMOD is available in this repository too. Here is a link to the new version, QSWATMOD2 [https://github.com/spark-brc/QSWATMOD2](https://github.com/spark-brc/QSWATMOD2). You will find the latest and useful information in [the SWAT-MODFLOW Google group](https://groups.google.com/forum/#!forum/swat-modflow). Also, it would be great if you can contribute to this tool.
