### ISSUE TITLE
"Getting maximum dhrus per HRU" in the "Create linkage files" stage reports an error

### ISSUE THREAD

**Issue by songyongyu** [spark-hydro/qswatmod-deprecated#2]
"Getting maximum dhrus per HRU" in the "create linkage files" stage reports an error. My own HRU file is compared with that in the example, and no exception is found.

![image](https://user-images.githubusercontent.com/90433532/136658670-b1b97c4d-ab23-424e-a950-60f2e77acc69.png)

**Comment by spark-hydro** [comment]
I am sorry for the inconvenience. This QSWATMOD version is no longer supported.
Please use QSWATMOD2 then if the issue still persists, let me know. Here is a link to QSWATMOD2.
https://github.com/spark-brc/QSWATMOD2
